from snowballing.models import Place, DB
from snowballing.common_places import *

n_3PGCIC = conference("3PGCIC", "International Conference on P2P, Parallel, Grid, Cloud and Internet Computing")

AAAI = conference("AAAI", "AAAI Conference on Artificial Intelligence")
AAAIWorkshop = conference("AAAI Workshop", "Workshop on Acquiring Planning Knowledge via Demonstration")
AADEBUG = conference("AADEBUG", "International Symposium on Automated And Analysis-Driven Debugging")
AAMAS = conference("AAMAS", "International conference on Autonomous agents and multi-agent systems")
AAI = journal("AAI", "Advances in Artificial Intelligence")
ACM_SE = conference("ACM SE", "Annual Southeast Regional Conference")
ACMAnuual = conference("<ACM Annual>", "ACM annual conference")
ACML = conference("ACM-L", "International Workshop on Active Conceputal Modeling of Learning")
ACMQ = magazine("ACMQ", "ACM Queue")
ACL = conference("<ACL>", "ACL Workshop on Effective Tools and Methodologies for Teaching NLP and Computational Linguistics")
ACSAC = conference("ACSAC", "Annual Computer Security Applications Conference")
ActaInformatica = journal("Acta Inf.", "Acta Informatica")
ADASS = conference("ADASS", "Astronomical Data Analysis Software and Systems")
ADC = conference("ADC", "Australasian Database Conference")
ADVCOMP = conference("ADVCOMP", "International Conference on Advanced Engineering Computing and Applications in Sciences")
AES = journal("AES", "Advances in Engineering Software")
AGILE = conference("AGILE Conference", "Conference of the Association of Geographic Information Laboratories for Europe") # Geographic Information Science at the Heart of Europe
AGTIVE = conference("AGTIVE", "International Symposium on Applications of Graph Transformations with Industrial Relevance")
AHM = conference("AHM", "UK e-Science All Hands Meeting")
AHSWN = journal("AHSWN", "Ad Hoc & Sensor Wireless Networks")
AI = journal("AI", "Artificial Intelligence")
AIAI = conference("AIAI", "International Conference on Artificial Intelligence Applications and Innovations")
AIC = journal("<AIC>", "AI Communications")
AICCSA = conference("AICCSA", "International Conference on Computer Systems and Applications")
AIM = journal("AIM", "Annals of Internal Medicine")
AISS = journal("AISS", "Advances in Information Sciences and Service Sciences")
ALS = conference("ALS", "Annual Linux Showcase and Conference")
AmJEpidemiol = journal("Am. J. Epidemiol.", "American Journal of Epidemiology")
AmMathMon = journal("Am. Math. Mon.", "The American Mathematical Monthly")
AMPTIAC_News = magazine("AMPTIAC Newsletter", "AMPTIAC Newsletter")
amstat = magazine("amstat", "Amstat News")
AnnApplStat = journal("Ann. Appl. Stat.", "The Annals of Applied Statistics")
AnnuRevEnvironResour = journal("Annu. Rev. Environ. Resour.", "Annual Review of Environment and Resources")
AnnuRevStatistics = journal("Annu. Rev. Stat. Appl.", "Annual Review of Statistics and Its Application")
AOIS = journal("AOIS", "Annals of Information Systems") # Semantic e-Science
AOSD_MISS = conference("AOSD-MISS", "AOSD Workshop on Modularity in Systems Software")
APL = journal("APL", "Applied Physics Letters")
ARA = journal("ARA", "Archives and Manuscripts")
ARCS = conference("ARCS", "International Conference on Architecture of Computing Systems")
ARES = conference("ARES", "International Conference on Availability, Reliability and Security")
AREPS = journal("AREPS", "Annual Review of Earth and Planetary Sciences")
ASA = conference("<ASA>", "American Statistical Association meetings")
ASCE = journal("ASCE", "Journal of Environmental Engineering")
ASE = conference("ASE", "IEEE/ACM International Conference on Automated Software Engineering")
ASHRAET = journal("ASHRAE", "ASHRAE Transactions")
ASIA_CCS = conference("ASIA CCS", "ACM symposium on Information, computer and communications security")
ASLDAM = journal("ASLDAM", "Advanced Science Letters")
ASPLOS = conference("ASPLOS", "International Conference on Architectural Support for Programming Languages and Operating Systems")
AstronComput = journal("Astron. Comput.", "Astronomy and Computing")
ATC = conference("ATC", "USENIX Annual Technical Conference")
ATIS = conference("ATIS", "International Conference on Applications and Techniques in Information Security")
AusDM = conference("AusDM", "Australasian Data Mining Conference")
AutoML = conference("AutoML", "AutoML Workshop")
AVI = conference("AVI", "Working Conference on Advanced Visual Interfaces")
AWC = conference("AWC", "Australasian Web Conference")

BAMS = journal("BAMS", "Bulletin of the American Meteorological Society")
BBIMFX = journal("BBIMFX", "Briefings in Bioinformatics")
BdCloud = conference("BdCloud", "International Conference on Big Data and Cloud Computing")
BIB = journal("<BIB>", "Brain imaging and behavior")
BIBMW = conference("BIBMW", "IEEE International Conference on Bioinformatics and Biomedicine Workshops")
BIGCOMP = conference("BIGCOMP", "International Conference on Big Data and Smart Computing")
bioinformatics = journal("bioinformatics", "Bioinformatics")
Biometrical = journal("Biometrical Journal", "Biometrical Journal")
biostatistics = journal("biostatistics", "Biostatistics")
BigData = conference("BigData", "IEEE International Conference on Big Data")
BMJ = journal("BMJ", "British Medical Journal")
BNCOD = conference("BNCOD", "British National Conference on Databases")
BPM = conference("BPM", "International Conference on Business Process Management")
bresciw = conference("BRESCI", "Brazilian e-Science Workshop")
BTW = conference("BTW", "Conference on Datenbanksysteme in Buisness, Technologie und Web (BTW)")


CARLA = conference("CARLA", "Latin American High Performance Computing Conferenc")
CACM = journal("CACM", "Communications of the ACM")
CaGIS = journal("CaGIS", "Cartography and Geographic Information Science")
CAiSE = conference("CAiSE", "International Conference on Advanced Information Systems Engineering")
CASCON = conference("CASCON", "Centre for Advanced Studies Conference")

CBMS = conference("CBMS", "International Symposium on Computer-Based Medical Systems")

CCGRID = conference("CCGrid", "IEEE/ACM International Symposium on Cluster, Cloud and Grid Computing")
CCPE = journal("CCPE", "Concurrency and Computation: Practice and Experience")
CCR = journal("CCR", "ACM SIGCOMM Computer Communication Review")
CCS = conference("CCS", "ACM Conference on Computer and Communications Security")

CDCIEM = conference("CDCIEM", "International Conference on Computer Distributed Control and Intelligent Environmental Monitoring")

CerCor = journal("CerCor", "Cerebral Cortex")
CESNET = conference("CESNET", "CESNET Conference")
CEURWS = conference("CEURWS", "Workshop on the Semantic Publishing")
CEUS = journal("<CEUS>", "Computers, Environment and Urban Systems")

CGO = conference("CGO", "International Symposium on Code Generation and Optimization")
CGeA = journal("CG&A", "IEEE computer graphics and applications")

CHASE = conference("CHASE", "International Workshop on Co-operative and Human Aspects of Software Engineering")
CHB = journal("CHB", "Computers in Human Behavior")
CHI = conference("CHI", "Conference on Human Factors in Computing Systems")

CIBEC = conference("CIBEC", "Cairo International Biomedical Engineering Conference")
CIC = conference("CIC", "International Conference on Collaboration and Internet Computing")
CIDR = conference("CIDR", "Conference on Innovative Data Systems Research")
CiI = journal("<CiI>", "Computers in Industry")
CIKM = conference("CIKM", "International Conference on Information and Knowledge Management")
CiSE = journal("CiSE", "Computing in Science & Engineering")
CISS = conference("CISS", "Catalan International Symposium on Statistics")
CIT = journal("CIT", "Journal of Computing and Information Technology")

CLIR = conference("CLIR", "Authenticity in the Digital Environment")
CLOUD = conference("CLOUD", "International Conference on Cloud Computing")
CloudCom = conference("CloudCom", "International Conference on Cloud Computing Technology and Science")
CLUSTER = conference("CLUSTER", "IEEE International Conference on Cluster Computing")
ClusterComputing = journal("Cluster Computing", "The Journal of Networks, Software Tools and Applications")

CMR = journal("<CMR>", "California Management Review")

CODATA = journal("<CODATA>", "Data Science Journal")
COGNITIVE = conference("COGNITIVE", "International Conference on Advanced Cognitive Technologies and Applications")
CollaborateCom = conference("CollaborateCom", "International Conference on Collaborative Computing: Networking, Applications and Worksharing")
CompGeo = journal("<CompGeo>", "Computers & Geosciences")
COMPSAC = conference("COMPSAC", "IEEE Annual Computer Software and Applications Conference")
COMPSACW = conference("COMPSACW", "IEEE Annual Computer Software and Applications Conference Workshops")
COMPSTAT = conference("COMPSTAT", "International Conference on Computational Statistics")
CompStatJournal = journal("Comp. Stat.", "Computational Statistics")
Computer = journal("Computer", "Computer")
Computing = journal("Computing", "Computing")
CON = journal("<CON>", "Current opinion in neurology")

CPC = journal("<CPC>", "Computer Physics Communications")

CS = journal("<CS>", "Complex Systems")
CSCW = conference("CSCW", "ACM Conference on Computer Supported Cooperative Work")
CSF = conference("CSF", "Computer Security Foundations Symposium")
CSMR = conference("CSMR", "European Conference on Software Maintenance and Reengineering")
CSUR = journal("CSUR", "ACM Computing Surveys")
CSCWD = conference("CSCWD", "International Conference on Computer Supported Cooperative Work in Design")

CTS = conference("CTS", "International Symposium on Collaborative Technologies and Systems")

CurrBio = journal("Curr. Bio.", "Current Biology")
CurrProtInBioinformatics = journal("Curr. Prot. in Bioinformatics", "Current Protocols in Bioinformatics")

CVSM = conference("CVSM", "Workshop on Comparison and Versioning of Software Models")


DASC = conference("DASC", "International Conference on Dependable, Autonomic and Secure Computing")
DASFAA = conference("DASFAA", "International Conference on Database Systems for Advanced Applications")
Datamation = magazine("Datamation", "Datamation")
DBKDA = conference("DBKDA", "International Conference on Advances in Databases, Knowledge, and Data Applications")
DBPL = conference("DBPL", "International Symposium on Database Programming Languages")
DCMI = conference("DCMI", "International Conference on Dublin Core")
DDT = journal("<DDT>", "Drug Discovery Today")
DEBS = conference("DEBS", "ACM international conference on Distributed event-based systems")
DEBULL = journal("DEBULL", "IEEE Data Engineering Bulleting")
DEEM = conference("DEEM", "Workshop on Data Management for End-to-End Machine Learning")
DeSE = conference("DeSE", "International Conference on the Developments in E-Systems Engineering")
DEST = conference("DEST", "IEEE International Conference on Digital Ecosystems and Technologies")
DevNeurobiol = journal("Dev. Neurobiol.", "Developmental Neurobiology")
DEXA = conference("DEXA", "International Conference on Database and Expert Systems Applications")
DF = journal("<DF>", "Digital Fingerprinting")
DG_O = conference("dg.o", "National Conference on Digital Government Research")
DILS = conference("DILS", "International Conference on Data Integration") # Data Integration in the Life Sciences
DIMVA = conference("DIMVA", "SIG SIDAR Conference on Detection of Intrusions and Malware & Vulnerability Assessment")
DISCS = conference("DISCS", "IEEE International Workshop on Data Intensive Scalable Computing Systems")
DKE = journal("DKE", "Data and Knowledge Engineering")
DLIB = magazine("D-Lib", "D-Lib Magazine")
DMKDFD = journal("DMKDFD", "Data Mining and Knowledge Discovery")
DMS = conference("DMS", "International Conference on Distributed Multimedia Systems")
DMSN = conference("DMSN", "Proceedings of the Workshop on Data Management for Sensor Networks")
DPDB = journal("<DPDB>", "Distributed and Parallel Databases")
DPDM = journal("DPDM", "Data Provenance and Data Management in eScience")
DPIF = conference("DPIF", "Digital Preservation Interoperability Framework Workshop")
DSEP = conference("DSEP", "Workshop on Data Streams and Event Processing")
DSN = conference("DSN", "IEEE/IFIP International Conference on Dependable Systems and Networks")
DSS = journal("DSS", "Decision Support Systems")

EA = journal("<EA>", "Experimental Astronomy")
EASE = conference("EASE", "Evaluation and Assessment in Software Engineering")
EC = journal("EC", "Entertainment Computing")
EC2ND = conference("EC2ND", "European Conference on Computer Network Defense")
ECCS = conference("ECCS", "European Conference on Curriculum Studies")
ECCM_ECFD = conference("ECCM-ECFD", "European Conference on Computational Fluid Dynamic")
ECDL = conference("ECDL", "Workshop on Web Archives")
ECEASST = journal("ECEASST", "ECEASST—Electronic Communications of the EASST")
ECML_PKDD = conference("ECML-PKDD", "The European Conference on Machine Learning and Principles and Practice of Knowledge Discovery")
EcoInformatics = journal("Ecoinformatics", "Ecological Informatics")
ECOOP = conference("ECOOP", "Object-Oriented Programming")
EDA_PS = conference("EDA-PS", "International Workshop on Event-driven Architecture, Processing and Systems")
EDBT = conference("EDBT", "International Conference on Extending Database Technology")
EDBT_ICDT = conference("EDBT/ICDT", "Joint EDBT/ICDT Workshops")
EDOCW = conference("EDOCW", "IEEE International Enterprise Distributed Object Computing Conference Workshops")
EIM = conference("EIM", "Proceedings of the Environmental Information Management Conference")
EKAW = conference("EKAW", "European Knowledge Acquisition Workshop")
EMS = journal("<EMS>", "Environmental Modelling & Software")
Environments = journal("Environments", "Environments")
ER = conference("ER", "International Conference on Conceptual Modeling")
ESA = journal("<ESA>", "Expert Systems with Applications")
eScience = conference("eSoN", "International Conference on E-Science")
ESEC_FSE = conference("ESEC_FSE", "Joint Meeting of the European Software Engineering Conference and the ACM SIGSOFT Symposium on the Foundations of Software Engineering")
ESEM = conference("ESEM", "International Symposium on Empirical Software Engineering and Measurement")
ESIN = journal("ESIN", "Earth Science Informatics")
eSoN = eScience
ESSci = journal("<ESSci>", "Earth and Space Science")
ESTC = conference("ESTC", "Earth Science Technology Conference")
ESWC = conference("ESWC", "Extended Semantic Web Conference")
EuroPar = conference("Euro-Par", "European Conference on Parallel Processing")
EuroSys = conference("EuroSys", "ACM European Conference on Computer Systems")
EuroVis = conference("EuroVis", "Eurographics Conference on Visualization")
EXPCS = conference("EXPCS", "Workshop on Experimental Computer Science")

F1000Research = journal("F1000Research", "F1000Research")
FAST = conference("FAST", "USENIX Conference on File and Storage Technologies")
FGCS = journal("FGCS", "Future Generation Computer Systems")
FIS = conference("FIS", "Future Internet Symposium")
FNCom = journal("fncom", "Frontiers in Computational Neurosciences")
FNInf = journal("fninf", "Frontiers in Neuroinformatics")
FNIns = journal("fnins", "Frontiers in Neuroscience")
FNIps = journal("fnips", "Frontiers in Plant Science")
FormaliSE = conference("FormaliSE", "FME Workshop on Formal Methods in Software Engineering")
FundationsAndTrendsInWebScience = journal("Foundations and Trends in Web Science", "Foundations and Trends in Web Science")
FRCSS = conference("FRCSS", "Workshop on future research challenges for software and services")
FTB = journal("<FTB>", "Foundations and Trends in Databases")

GBC = journal("GBC", "Global Biogeochemical Cycles")
GCC = conference("GCC", "International Conference on Grid and Cooperative Computing")
GCE = conference("GCE", "Grid Computing Environments Workshop")
GCM = conference("GCM", "International Workshop on Graph Computation Models")
GD = conference("GD", "International Symposium on Graph Drawing")
GECON = conference("GECON", "International Conference on Grid Economics and Business Models")
Genomics = journal("Genomics", "Genomics")
GenomeBiol = journal("Genome Biol.", "Genome Biology")
GeoInfo = conference("GeoInfo", "Brazilian Symposium on Geoinformatics")
GeoInformatics = conference("Geoinformatics", "International Conference on Geoinformatics")
GEOProcessing = conference("GEOProcessing", "International Conference on Advanced Geographic Information Systems, Applications, and Services")
GigaScience = journal("GigaScience", "GigaScience")
GITAM = journal("GITAM", "Journal of Information Technology Applications and Management")
Globe = conference("Globe", "International Conference on Data Management in Cloud, Grid and P2P Systems")
GMD = journal("GMD", "Geoscientific Model Development")
GPCE = conference("GPCE", "International Conference on Generative Programming: Concepts & Experiences")
GTE = conference("<GTE>", "Workshop on Software Engineering Environments for Programming-in-the-Large")
GPCE = conference("GPCE", "International Conference on Generative Programming and Component Engineering")
GraBaTs = conference("GraBaTs", "International Workshop on Graph-Based Tools")
GS = journal("<GS>", "Genome Research")

HandbookStatistics = journal("Handbook of Statistics", "Handbook of Statistics")
HAISA = conference("HAISA", "International Symposium on Human Aspects of Information Security & Assurance")
HASE = conference("HASE", "International Symposium on High Assurance Systems Engineering")
HCLS = conference("HCLS", "The Future of the Web for Collaborative Science")
HCOMP = conference("HCOMP", "AAAI Conference on Human Computation and Crowdsourcing")
HealthGrid = conference("HealthGrid", "Healthgrid Applications and Core Technologies")
HEALTHINF = conference("HEALTHINF", "International Conference on Health Informatics")
HealthNet = conference("HealthNet", "SIGMOBILE International Workshop on Systems and Networking Support for Healthcare and Assisted Living Environments")
HESS = journal("HESS", "Hydrology and Earth System Sciences")
HICSS = conference("HICSS", "International Conference on System Sciences")
HILDA = conference("HILDA", "Proceedings of the Workshop on Human-In-the-Loop Data Analytics")
HiPC = conference("HiPC", "International Conference on High Performance Computing") # Workshop on Grid and Utility Computing
HOSC = journal("HOSC", "Higher-Order and Symbolic Computation")
HotCloud = conference("HotCloud", "USENIX Workshop on Hot Topics in Cloud Computing")
HotOS = conference("HotOS", "USENIX Workshop on Hot Topics in Operating Systems")
HotSec = conference("HotSec", "USENIX Conference on Hot Topics in Security")
HotStorage = conference("HotStorage", "USENIX File System Workshop")
HPCA = conference("HPCA", "International Symposium on High Performance Computer Architecture")
HPCC_EUC = conference("HPCC_EUC", "International Conference on High Performance Computing and Communications & International Conference on Embedded and Ubiquitous Computing")
HPDC = conference("HPDC", "International Symposium on High Performance Distributed Computing")
HPDS = conference("HPDS", "IEEE Symposium on High Performance Distributed Systems")
HSR = journal("HSR", "Historical Social Research/Historische Sozialforschung")
HT = conference("HT", "ACM Conference on Hypertext and Hypermedia")
HVC = conference("HVC", "Haifa Verification Conference")


IAAI = conference("IAAI", "International conference on Innovative applications of artificial intelligence")
IADC = conference("IADC", "International Advanced Database Conference")
IAI = journal("IAI", "Infection and Immunity")
IAPR = conference("IAPR", "Workshop on Graph-based Representations in Pattern")
IARIA = journal("IARIA", "International Journal on Advances in Intelligent Systems")

IBM_RD = journal("IBM_RD", "IBM Journal of Research and Development")

IC = journal("IC", "IEEE Internet Computing")
IC3K = conference("IC3K", " International Joint Conference on Knowledge Discovery, Knowledge Engineering, and Knowledge Management")
ICACT = conference("ICACT", "International Conference on Advanced Communication Technology")
ICAISC = conference("ICAISC", "International Conference on Artificial Intelligence and Soft Computing")
ICAT = conference("ICAT", "International Conference on Advanced Technology & Sciences")
ICBO = conference("ICBO", "International Congress of Behavioural Optometry")
ICCC = conference("ICCC", "International Conference on Computational Cybernetics")
ICCIS = conference("ICCIS", "International Conference on Computational and Information Sciences")
ICCRTS = conference("ICCRTS", "International Command and Control Research and Technology Symposium")
ICCS = conference("ICCS", "International Conference on Computer Science")
ICCSNT = conference("ICCSNT", "International Conference on Computer Science and Network Technology")
ICDCS = conference("ICDCS", "International Conference on Distributed Computing Systems")
ICDE = conference("ICDE", "International Conference on Data Engineering")
ICDMW = conference("ICDMW", "International Conference on Data Mining Workshop")
ICDT = conference("ICDT", "International Conference on Database Theory")
ICEC = conference("ICEC", "Annual International Conference on Electronic Commerce")
ICESM = conference("ICESM", "International Conference on Earth System Modelling")
ICETC = conference("ICETC", "International Conference on Education Technology and Computer")
ICFP = conference("ICFP", "International Conference on Functional Programming")
ICIS = conference("ICIS", "International Conference on Intelligent Computing and Intelligent Systems")
ICIS2 = conference("ICIS-2", "International Conference on Computer and Information Science")
ICIS3 = conference("ICIS-3", "International Conference on Information Systems")
ICITCS = conference("ICITCS", "International Conference on IT Convergence and Security")
ICKMKT = conference("ICKMKT", "International Conference on Knowledge Management and Knowledge Technologies")
ICML = conference("ICML", "International Conference on Machine Learning")
ICNS = conference("ICNS", "International Conference on Networking and Services")
ICOOOLPS = conference("ICOOOLPS", "Workshop on the Implementation, Compilation, Optimization of Object-Oriented Languages and Programming Systems")
ICSC = conference("ICSC", "International Conference on Semantic Computing")
ICSE = conference("ICSE", "International Conference on Software Engineering")
ICSM = conference("ICSM", "International Conference on Software Maintenance")
ICSSP = conference("ICSSP", "International Conference on Software and System Process")
ICST = conference("ICST", "IEEE International Conference on Software Testing")
ICTD = conference("ICTD", "ACM/IEEE International Conference on Information and Communication Technologies and Development")
ICT_EURASIA = conference("ICT-EURASIA", "Information and Communication Technology-EurAsia Conference")
ICWS = conference("ICWS", "IEEE International Conference on Web Services")
ICWSM = conference("ICWSM", "Workshop on Standards and Practices in Large-Scale Social Media Research")

IDCC = conference("IDCC", "International Digital Curation Conference")
IDEAS = conference("IDEAS", "Database Engineering and Application Symposium")

IEEE = journal("IEEE", "Proceedings of the IEEE")
IEEE_Bulletin = journal("IEEE Data Engineering Bulletin",  "IEEE Data Engineering Bulletin")
IEEE_DesignTest = journal("IEEE Design & Test", "IEEE Design & Test")
IEEE_IntellSyst = journal("IEEE Intell. Sysy.", "IEEE Intelligent Systems")
IEEE_SP = conference("IEEE_SP", "IEEE Symposium on Security and Privacy")
IEEE_VIS = conference("IEEE_VIS", "IEEE Visualization Conference")
iEMSs = conference("iEMSs", "International Congress on Environmental Modelling and Software")

IFIP_AICT = journal("IFIP AICT", "IFIP Advances in Information and Communication Technology")
IFIP_SEC = conference("IFIP SEC", "International Information Security Conference")
IFIP_WG = conference("IFIP WG", "International Workshop on Open Problems in Network Security")
IFIPTM = conference("IFIPTM", "IFIP International Conference on Trust Management")

IGARSS = conference("IGARSS", "IEEE International Geoscience and Remote Sensing Symposium")

IIWAS = conference("IIWAS", "International Conference on Information Integration and Web-based Applications & Services")

IJAAS = journal("<IJAAS>", "International Journal of Automation and Autonomous System")
IJACSA = journal("IJACSA", "International Journal of Advanced Computer Science and Applications")
IJACT = journal("IJACT", "Journal of Advanced Computer Technology “COMPUSOFT”")
IJAEIS = journal("IJAEIS", "International Journal of Agricultural and Environmental Information Systems")
IJARCSSE = journal("IJARCSSE", "International Journal of Advanced Research in Computer Science and Software Engineering")
IJBDI = journal("IJBDI", "International Journal of Big Data Intelligence")
IJBPIM = journal("IJBPIM", "International Journal of Business Process Integration and Management")
IJCA = journal("IJCA", "International Journal of Computer Applications") # IJ Comput. Appl
IJCSIT = journal("IJCSIT", "International Journal of Computer Science and Information Technologies")
IJCSMC = journal("IJCSMC", "International Journal of Computer Science and Mobile Computing")
IJDC = journal("IJDC", "International Journal of Digital Curation")
IJDLS = journal("IJDLS", "International Journal on Digital Libraries")
IJETR = journal("IJETR", "International Journal of Engineering & Technical Research")
IJGUC = journal("IJGUC", "International Journal of Grid and Utility Computing")
IJHCS = journal("<IJHCS>", "International Journal of Human-Computer Studies")
IJIS = journal("IJIS", "International journal of information security")
IJISCA = journal("IJISCA", "International Journal of Information Science and Computer Applications")
IJITCS = journal("IJITCS", "International Journal of Information Technology and Computer Science")
IJITR = journal("IJITR", "International Journal of Innovative Technology and Research")
IJITWE = journal("IJITWE", "International Journal of Information Technology and Web Engineering")
IJMSO = journal("IJMSO", "International Journal of Metadata, Semantics and Ontologies")
IJNM = journal("<IJNM>", "International Journal of Network Management")
IJOCI = journal("IJOCI", "International Journal of Organizational and Collective Intelligence")
IJPP = journal("IJPP", "International Journal of Parallel Programming")
IJSER = journal("IJSER", "International Journal of Scientific & Engineering Research")
IJSIA = journal("IJSIA", "International Journal of Security and its Applications")
IJSWIS = journal("IJSWIS", "International Journal on Semantic Web and Information Systems")
IJWSR = journal("IJWSR",  "International Journal of Web Services Research")

IKC = conference("IKC", "International KEYSTONE Conference")

IMCOM = conference("IMCOM", "International Conference on Ubiquitous Information Management and Communication")
IMMOA = conference("IMMOA", "International Workshop on Information Management for Mobile Applications")

INC = conference("INC", "International Network Conference")
INES = conference("INES", "International Conference on Intelligent Engineering Systems")
Information = journal("Information", "International Information Institute - Information")
InfVis = journal("<InfVis>", "Information Visualization")
Interface = conference("Interface", "Symposium on the Interface of Computing Science and Statistics")
IntJHighPerformComputAppl = journal("Int. J. High Perform, Comput. Appl.", "International Journal of Supercomputer Applications and High Performance Computing")
IntJNetwVirtualOrgan = journal("Int. J. Netw. Virtual Organ.", "International journal of networking and virtual organisations")

IOPE = conference("IOPE", "Workshop on Identifying objects, processes and events in spatio-temporally distributed data")

IPAW = conference("IPAW", "International Provenance and Annotation Workshop")
IPDPS = conference("IPDPS", "IEEE International Parallel Distributed Processing Symposium")
IPDPSW  = conference("IPDPSW", "IEEE International Parallel and Distributed Processing Symposium Workshops & PhD Forum")
IPL = journal("IPL", "Information Processing Letters")
IPM = journal("IPM", "Information Processing and Management")
IPMU = conference("IPMU", "International Conference on Information Processing and Management of Uncertainty in Knowledge-Based Systems")
iPRES = conference("iPRES", "International Conference on Digital Preservation")
IPSN = conference("IPSN", "International Conference on Information Processing in Sensor Networks")

IRI = conference("IRI", "International Conference on Information Reuse and Integration")

IS = journal("Inf. Syst.", "Information Systems")
ISCA = conference("ISCA", "International Symposium on Computer Architecture")
ISCB = conference("ISCB", "International Conference on Intelligent Systems for Molecular Biology")
ISCIT = conference("ISCIT", "International Symposium on Communications and Information Technologies")
ISPA = conference("ISPA", "International Symposium on Parallel and Distributed Processing with Applications")
ISPRS = journal("ISPRS", "Journal of Photogrammetry and Remote Sensing")
IS_EUD = conference("IS-EUD", "International Symposium on End User Development")
ISGC = conference("ISGC", "International Symposium on Grids and Clouds")
ISJ = journal("ISJ", "IEEE Systems Journal")
ISMIR = conference("ISMIR", "International Society for Music Information Retrieval Conferenc")
ISPRS = journal("ISPRS", "ISPRS Journal of Photogrammetry and Remote Sensing")
iSociety = conference("i-Society", "International Conference on Information Society")
ISoLA = conference("ISoLA", "International Symposium on Leveraging Applications of Formal Methods, Verification and Validation")
ISORC = conference("ISORC", "IEEE International Symposium on Real-Time Computing")
ISSTA = conference("ISSTA", "ACM International Symposium on Software Testing and Analysis")
IST = journal("<IST>", "Information and Software Technology")
ISVC = conference("ISVC", "International Symposium on Visual Computing")
ISWC = conference("ISWC", "International Semantic Web Conference")

ITBAM = conference("ITBAM", "International Conference on Information Technology in Bio-and Medical Informatics")
ITI = conference("ITI", "International Conference on Information Technology Interfaces")

IUCr = journal("IUCr", "Acta Crystallographica Section D: Biological Crystallography")
IUI = conference("IUI", "International ACM Conference on Intelligent User Interfaces")

IWPSE = conference("IWPSE", "International Workshop on Principles of Software Evolution")


JAIS = journal("JAIS", "Journal of the Association for Information Systems")
JAIR = journal("JAIR", "Journal of Artificial Intelligence Research")
JAMA = journal("JAMA", "Journal of American Medical Association")
JARA_HPC = conference("JARA-HPC", "JARA High-Performance Computing Symposium")
JArtifSocSoc = journal("J. Artif. Soc. Soc.", "Journal of Artificial Societies and Social Simulation")
JASMS = journal("JASMS", "Journal of the American Society for Mass Spectrometry")
JASP = journal("JASP", "EURASIP Journal on Advances in Signal Processing")

JBCS = journal("JBCS", "Journal of the Brazilian Computer Society")
JBIOBL = journal("JBIOBL", "Journal of Biomedical Informatics")

JCDL = conference("JCDL", "ACM/IEEE-CS joint conference on Digital libraries")
JCE = journal("JCE", "Journal of Clinical Epidemiology")
JCGS = journal("JCGS", "Journal of Computational and Graphical Statistics")
JCIS = journal("JCIS", "Journal of Communication and Information Systems")
JCKBSE = conference("JCKBSE", "Joint Conference on Knowledge-Based Software Engineering")
JCS = journal("JCS", "Journal of Computer Security")
JCSE = journal("JCSE", "Journal of Computing Science and Engineering")
JCSS = journal("JCSS", "Journal of Computer and System Sciences")

JDIQ = journal("JDIQ", "Journal of Data and Information Quality")
JDM = journal("JDM", "Journal of Database Management")

JETA = journal("JETA", "Journal of Emerging Technologies in Accounting")

JGCOAP = journal("JGCOAP", "Journal of Grid Computing")

JH = journal("J. Hydroinform.", "Journal of Hydroinformatics")
JH2 = journal("J. Hydrology", "Journal of Hydrology")

JIB = journal("JIB", "Journal of Integrative Bioinformatics")
JIDM = journal("JIDM", "Journal of Information and Data Management")
JIIS = journal("JIIS", "Journal of Intelligent Information Systems")
JILP = journal("JILP", "The Journal of Instruction-Level Parallelism")
JIPS = journal("JIPS", "Journal of Information Processing Systems")

JKICS = journal("J-KICS", "The Journal of Korean Institute of Communications and Information Sciences")

JLP = journal("JLP", "The Journal of Logic Programming")

JMCB = journal("JMCB", "Journal of Money, Credit and Banking")
JMLR = journal("JMLR", "Journal of Machine Learning Research")
JMolBiol = journal("J. Mol. Biol.", "Molecular Biology")

JNEUROSCI = journal("JNEUROSCI", "Journal of Computational Neuroscience")

JOCS = journal("JOCS", "Journal of Computational Science")
JoDS = journal("JoDS", "Journal on Data Semantics")
JOICS = journal("JOICS", "Journal of Information and Computational Science")
JORS = journal("JORS", "Journal of Open Research Software")
JourVisLangComput = journal("<Jour. Vis. Lang. Comput.>", "Journal of Visual Languages & Computing")

JPCS = conference("JPCS", "Journal of Physics: Conference Series")
JPhisiolParis = journal("J. Physiol. Paris", "Journal of Physiology Paris")

JSAC = journal("JSAC", "IEEE Journal on Selected Areas in Communications")
JSC = journal("JSC", "Journal of Scientific Computing")
JSM = conference("JSM", "Joint Statistical Meetings")
JSoftwEngStud = journal("J. Softw. Eng. Stud.", "Journal of Software Engineering Studies")
JSSPP = conference("JSSPP", "International Workshop on Job Scheduling Strategies for Parallel Processing")
JSTARS = journal("J-STARS", "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing")
JStatSoft = journal("J. Stat. Soft.", "Journal of Statistical Software")
JSW = journal("JSW", "Journal of Software")

JUCS =journal("J. UCS", "Journal of Universal Computer Science")


KBS = journal("KBS", "Knowledge-Based Systems")
KCAP = conference("K-CAP", "International Conference on Knowledge Capture")
KDD = conference("KDD", "International Conference on Knowledge Discovery and Data Mining")
KER = journal("KER", "The Knowledge Engineering Review")
KR = conference("KR", "International Conference on Principles of Knowledge Representation and Reasoning")

LDOW = conference("LDOW", "Workshop on Linked Data on the Web")
LIBERQ4 = journal("<LIBERQ4>", "Liber Quarterly")
LibraryTrends = journal("LibraryTrends", "Library Trends")
LinuxJournal = magazine("Linux Journal", "Linux Journal")
LISA = conference("LISA", "USENIX Large Installation System Administration")
LISS = conference("LISS", "International Conference on Logistics, Informatics and Service Sciences")
LHS = journal("LHS", "Learning Health Systems")
LWDA = conference("LWDA", "Lernen Wissen Daten Analysen")

MAI = journal("<MAI>", "Annals of Mathematics and Artificial Intelligence")
MDAI = conference("MDAI", "Modeling Decisions for Artificial Intelligence")
MEDI = conference("MEDI", "International Conference on Model and Data Engineering")
MGC = conference("MGC", "Workshop on Middleware for Grid Computing")
MIB = journal("MIB", "Molecular Imaging and Biology")
MICRO = conference("MICRO", "IEEE/ACM International Symposium on Microarchitecture")
MILCOM = conference("MILCOM", "IEEE Military Communications Conference")
MIPRO = conference("MIPRO", "International Convention on Information and Communication Technology, Electronics and Microelectronics")
MISQ = journal("MISQ", "Management Information Systems Quarterly")
ML = journal("ML", "Machine Learning Journal")
MobiSys = conference("MobiSys", "Annual International Conference on Mobile Systems, Applications, and Services")
MoBS = conference("MoBS", "Annual Workshop on Modeling, Benchmarking and Simulation")
MODELS = conference("MODELS", "International Workshop on Models")
MODSIM = conference("MODSIM", "International Congress on Modelling and Simulation")
MSCS = journal("MSCS", "Mathematical Structures in Computer Science")
MSeScienceW = conference("<MS eSci Work>", "Microsoft eScience Workshop")
MSR = conference("MSR", "Conference on Mining Software Repositories")

Nanotechnology = journal("Nanotechnology", "Nanotechnology")
NARHAD = journal("NARHAD", "Nucleic Acids Research")
NatGenet = journal("Nat. Genet.", "Nature Genetics")
NatMed = journal("Nat. Med.", "Nature Medicine")
Nature = journal("Nature", "Nature")
NBIS = conference("NBIS", "International Conference on Network-Based Information Systems")
NBT = journal("NBT", "Nature Biotechnology")
NCGIA = conference("<NCGIA>", "Workshop on Annotation and Resource Discovery of Geographic Image Data")
NDSS = conference("NDSS", "The Network and Distributed System Security Symposium")
NET = journal("NET", "Nuclear Engineering and Technology")
NetDB = conference("NetDB", "Workshop on Networking Meets Databases")
NeuralComputation = journal("Neural Comput.", "Neural Computation")
Neuroimage = journal("Neuroimage", "Neuroimage")
Neuroinformatics = journal("Neuroinformatics", "Neuroinformatics")
Neuron = journal("Neuron", "Neuron")
Neuroscience = journal("Neuroscience", "Neuroscience")
NGMAST = conference("NGMAST", "International Conference on Next Generation Mobile Apps, Services and Technologies")
NHESS = journal("NHESS", "Natural Hazards and Earth System Sciences")
NIPS = conference("NIPS", "Conference on Neural Information Processing Systems")
NIT = conference("NIT", "International Conference on New Information Technology")
NSDI = conference("NSDI", "USENIX Symposium on Networked Systems Design and Implementation")
NWeSP = conference("NWeSP", "International Conference on Next Generation Web Services Practices")
NYSDS = conference("NYSDS", "New York Scientific Data Summit")

ODBASE = conference("ODBASE", "International Conference on Ontologies, Databases and Applications of SEmantics")
OIR = journal("<OIR>", "Online Information Review")
OLS = conference("OLS", "Ottawa Linux Symposium")
Onward = conference("Onward", "International Symposium on New Ideas, New Paradigms, and Reflections on Programming & Software")
OOOOJournal = journal("OOOOJournal", "Oral surgery, oral medicine, oral pathology, oral radiology, and endodontology")
OOPSLA = conference("OOPSLA", "International Conference on Object Oriented Programming Systems, Languages, and Applications")
OSDI = conference("OSDI", "USENIX Symposium on Operating Systems Design and Implementation")
OSR = journal("OSR", "SIGOPS Operating Systems Review")
OTM = conference("OTM", "On the Move to Meaningful Internet Systems")


PacificVis = conference("PacificVis", "Pacific Visualization Symposium")
PACBB = conference("PACBB", "International Conference on Practical Applications of Computational Biology & Bioinformatics")
PACT = conference("PACT", "International Conference on. Parallel Architectures and Compilation Techniques")
PADD = conference("PADD", "ACM SIGPLAN and SIGOPS Workshop on Parallel and Distributed Debugging")
PASSAT = conference("PASSAT", "International Conference on Social Computing and Privacy,Security, Risk and Trust")
PASTE = conference("PASTE", "Workshop on Program Analysis for Software Tools and Engineering")

PBio = journal("PBio", "PloS Biology")
PBMB = journal("<PBMB>", "Progress in biophysics and molecular biology")

PCBI = journal("PCBI", "PLOS Computational Biology")
PCT = conference("PCT", "International Scientific Conference on Parallel Computing Technologies")

PDP = conference("PDP", "Euromicro International Conference on Parallel, Distributed and Network-Based Processing")
PDSW = conference("PDSW", "Parallel Data Storage Workshop")

PEPM = conference("PEPM", "ACM SIGPLAN Workshop on Partial Evaluation and Program Manipulation")
PeerJ = journal("PeerJ", "PeerJ")
PETRI_NETS = conference("PETRI_NETS", "International Conference on Applications and Theory of Petri Nets")

PLDI = conference("PLDI", "ACM SIGPLAN Conference on Programming Language Design and Implementation")
PLOSMed = journal("PLOSMed", "PLOS Medicine")
PLOSOne = journal("PLOSOne", "PLOS One")

PNAS = journal("PNAS", "Proceedings of the National Academy of Sciences")

PODC = conference("PODC", "ACM Symposium on Principles of Distributed Computing")
PODS = conference("PODS", "ACM Symposium on Principles of Database Systems")
POLICY = conference("POLICY", "IEEE International Symposium on Policies for Distributed Systems and Networks")
POPL = conference("POPL", "Principles of Programming Languages")

PPAM = conference("PPAM", "International Conference on Parallel Processing and Applied Mathematics")
PPDP = conference("PPDP", "International Symposium on Principles and Practice of Declarative Programming")
PPoPP = conference("PPoPP", "Principles and Practice of Parallel Programming")

PRDC = conference("PRDC", "International Symposium on Dependable Computing")
PREDON_WSDP = conference("PREDON", "PREDON Workshop on Scientific Data Preservation")
Procedia = journal("Procedia", "Procedia Computer Science")
ProvWeek = conference("Provenance Week", "Provenance Week")

PST = conference("PST", "Annual Conference on Privacy, Security and Trust")

Publications = journal("Publications", "Publications")
PUC = journal("PUC", "Personal and Ubiquitous Computing")

PV = conference("PV", "Ensuring the Long-Term Preservation and Value Adding to Scientific and Technical Data")

PyCon = conference("PyCon", "PyCon")
PyHPC = conference("PyHPC", "Workshop on Python for High-Performance and Scientific Computing")


QDB_MUD = conference("QDB/MUD", "<QDB/MUD>")
QRS_C = conference("QRS-C", "International Conference on Software Quality, Reliability and Security-Companion")
QSIC = conference("QSIC", "International Conference on Quality Software")
QUF = conference("QUF", "International QEMU Users’ Forum")

RAID = conference("RAID", "International Symposium on Research in Attacks, Intrusions and Defenses")
RCIS = conference("RCIS", "International Conference on Research Challenges in Information Science")
REP_XSEDE = conference("XSEDE", "The reproducibility at XSEDE workshop")
RDCEP = journal("RDCEP", "RDCEP Working Paper")
RE = conference("RE", "International Requirements Engineering Conference")
RECOMB = conference("RECOMB", "International Conference on Research in Computational Molecular Biology")
RED = conference("RED", "International Workshop on Resource Discovery")
RITA = journal("RITA", "Revista de Informática Teórica e Aplicada")
RSE = journal("RSE", "Remote Sensing of Environment")
RSSE = conference("RSSE", "International Workshop on Recommendation Systems for Software Engineering")
RSTL = journal("RSTL", "Philosophical Transactions of the Royal Society of London")

SAGMB = journal("SAGMB", "Statistical Applications in Genetics and Molecular Biology")
SAI = conference("SAI", "Science and Information Conference")
SAICSIT = conference("SAICSIT", "Annual Research Conference of the South African Institute of Computer Scientists and Information Technologists")

SBBD = conference("SBBD", "Brazilian Symposium on Databases")
SBCARS = conference("SBCARS", "Brazilian Symposium on Software Components, Architectures and Reuse")
SBES = conference("SBES", "Brazilian Symposium on Software Engineering")
SBGAMES = conference("SBGAMES", "Brazilian Symposium on Games and Digital Entertainment")
SBSeg = conference("SBSeg", "Simpósio Brasileiro em Segurança da Informação e de Sistemas Computacional")
SC = journal("SC", "State of the Practice Reports")
SC2 = journal("SC", "International Conference for HPC Networking, Storage and Analysis")
SCA = journal("SCA", "Software and Cyberinfrastructure for Astronomy")
SCC = conference("SCC", "IEEE International Conference on Services Computing")
SCFBM = journal("SCFBM", "Source Code for Biology and Medicine")
SciDAC = conference("SciDAC", "SciDAC Conference")
Science = journal("Science", "Science")
SCIKNOW = conference("SCIKNOW", "International Workshop on Capturing Scientific Knowledge")
SciPy = conference("SciPy", "Python in Science Conference")
Scholarpedia = journal("Scholarpedia", "Scholarpedia")
SCM = conference("SCM", "International Workshop on Software Configuration Management")
SCP = journal("SCP", "Science of Computer Programming")
SDE = conference("SDE", "ACM SIGSOFT/SIGPLAN Software Engineering Symposium on Practical Software Development Environments")
SDM = conference("SDM", "Workshop on Secure Data Management")
SECDEV = conference("SecDev", "IEEE Cybersecurity Development Conference")
SECSE = conference("SECSE", "International Workshop on Software Engineering for Computational Science and Engineering")
SecureCloud = conference("SecureCloud", "Secure Cloud Computing")
Security = conference("Security", "USENIX Security Symposium")
SEG = conference("SEG", "International Meeting of the Society of Exploration Geophysics")
SEKE = conference("SEKE", "International Conference on Software Engineering and Knowledge Engineering")
SEMANTiCS = conference("SEMANTiCS", "International Conference on Semantic Systems")
SemAudio = conference("<SemAudio>", "AES International Conference on Semantic Audio")
SEMISH = conference("SBC-SEMISH", "Seminário Integrado de Software e Hardware")
SenHP = conference("<SenHP>", "Dagstuhl Seminar on Semantic Aspects of Sensor Networks")
SePublica = conference("SePublica", "Workshop on Semantic Publications")
SERVICES = conference("SERVICES", "IEEE World Congress on Services")
SETIT = conference("SETIT", "International Conference on Sciences of Electronics, Technologies of Information and Telecommunications")
SETPC = journal("<SETPC>", "In Search of Elegance in the Theory and Practice of Computation")
SHTI = journal("<SHTI>", "Studies in Health Technology and Informatics")
SIAMJSciStatComput = journal("J.Sci. Stat. Comput.", "SIAM Journal on Scientific and Statistical Computing")
SIBGRAPI = conference("SIBGRAPI", "Conference on Graphics, Patterns and Images")
SID = journal("SID", "Scientific Information Database")
SIGACT = magazine("SIGACT News", "SIGACT News")
SIGAPP = conference("SIGAPP", "ACM Symposium on Applied Computing")
SIGKDDExplorations = journal("SIGKDD Explor. Newsl.", "SIGKDD Explorations")
SIGMETRICS = conference("SIGMETRICS", "International Conference on Measurements and Modeling of Computer Systems")
SIGMOD = conference("SIGMOD","ACM SIGMOD international conference on Management of data")
SIGMOD_PODS = conference("SIGMOD/PODS", "International Workshop on Workflow Approaches to New Data-centric Science")
SIGMOD_REC = journal("SIGMOD REC", "SIGMOD Record")
Significance = journal("Significance", "Significance")
SIGOPS = conference("SIGOPS", "Special Interest Group on Operating Systems")
SIGPLAN_NOTICES = journal("SIGPLAN Notices", "ACM SIGPLAN Notices")
SIGSPATIAL = conference("SIGSPATIAL", "ACM SIGSPATIAL International Conference on Advances in Geographic Information Systems")
SIMPDA = conference("SIMPDA", "International Symposium on Data-Driven Process Discovery and Analysis")
SITIS = conference("SITIS", "International Conference on Signal-Image Technology Internet-Based Systems")
SISS = conference("SISS", "Workshop on Data Sharing and Interoperability on the World-wide Sensor Web")
SISY = conference("SISY", "International Symposium on Intelligent Systems and Informatics")
SLE = conference("SLE", "ACM SIGPLAN International Conference on Software Language Engineering")
SOBRES = conference("SOBRES", "International Workshop on Software-Based Methods for Robust Embedded Systems")
SocialCom = conference("SocialCom", "International Conference on Social Computing")
SOCINFO = conference("SOCINFO", "International Workshop on Social Informatics")
SoftVis = conference("SoftVis", "ACM Symposium on Software Visualization")
Software = journal("Software", "IEEE Software")
SOSE = conference("SOSE", "IEEE Symposium on Service-Oriented System Engineering")
SOSP = conference("SOSP", "ACM Symposium on Operating Systems Principles")
SoSyM = journal("SoSyM", "Software and Systems Modeling")
SP = journal("SP", "Scientific Programming")
SPE = journal("SPE", "Software - Practice and Experience")
SPICES = conference("SPICES", "International Conference on Signal Processing, Informatics, Communication and Energy Systems")
SPLC = conference("SPLC", "Software Product Line Conference")
SPM = journal("SPM", "IEEE Signal Processing Magazine")
SPOT = conference("SPOT", "Workshop on Trust and Privacy on the Social and Semantic Web")
SQJ = journal("SQJ", "Software Quality Journal")
SSD = conference("SSD", "Symposium on Large Spatial Databases")
SSDBM = conference("SSDBM", "Scientific and Statistical Database Management")
SSN = conference("SSN", "International Conference on Semantic Sensor Networks")
StatisticsComputing = journal("Statistics and Computing", "Statistics and Computing")
STOC = conference("STOC", "ACM Symposium on Theory of Computing")
STTT = journal("STTT", "International Journal on Software Tools for Technology Transfer")
SummerSim = conference("SummerSim", "Summer Simulation Multi-Conference")
Super = journal("<Super>", "The Journal of Supercomputing")
SyntLecSemWeb = journal("<SyntLecSemWeb>", "Synthesis Lectures on the Semantic Web")
SWAT4LS = conference("SWAT4LS", "Semantic Web Applications and Tools for Life Sciences")
SWF = conference("SWF", "IEEE International Workshop on Scientific Workflows")
SWPM = conference("SWPM", "International Workshop on Role of Semantic Web in Provenance Management")
SW = journal("SW", "Semantic Web")

TASE = journal("TASE", "IEEE Transactions on Automation Science and Engineering")
TAOSD = journal("TAOSD", "Transactions on Aspect Oriented Software Development")
TaPP = conference("TaPP", "Workshop on the Theory and Practice of Provenance")
TBME = journal("TBME", "IEEE Transactions on Biomedical Engineering")
TC = journal("<TC>", "IEEE Transactions on Cybernetics")
TCBB = journal("TCBB", "Transactions on Computational Biology and Bioinformatics")
TCDE = journal("TCDE", "Bulletin of the Techinal Committee on Data Engineering")
TCS = journal("TCS", "Theoretical Computer Science")
TDSC = journal("TDSC", "IEEE Transactions on Dependable and Secure Computing")
Technology = journal("Technology", "Procedia Technology")
TEE = journal("<TEE>", "Trends in ecology & evolution")
TGIS = journal("<TGIS>", "Transactions in GIS")
TGRS = journal("TGRS", "IEEE Transactions on Geoscience and Remote Sensing")
TheLancet = journal("The Lancet", "The Lancet")
TiCS = journal("TiCS", "Trends in Cognitive Sciences")
TISSEC = journal("TISSEC", "ACM Transactions on Information and System Security")
TIST = journal("TIST", "ACM Transactions on Intelligent Systems and Technology")
TKDE = journal("TKDE", "IEEE Transactions on Knowledge and Data Engineering")
TLDKS = journal("TLDKS", "Transactions on large-scale data-and knowledge-centered systems")
TPDS = journal("TPDS", "IEEE Transactions on Parallel and Distributed Systems")
TPLP = journal("TPLP", "Theory and Practice of Logic Programming")
TMS_DEVS = conference("TMS/DEVS", "Symposium on Theory of Modeling & Simulation-DEVS Integrative")
TOCHI = journal("TOCHI", "ACM Transactions on Computer Human Interaction")
TOCS = journal("TOCS", "ACM Transactions on Computing Systems")
TODS = journal("TODS", "ACM Transactions on Database Systems")
TOIT = journal("TOIT", "ACM Transactions on Internet Technology")
TOMS = journal("TOMS", "ACM Transactions on Mathematical Software")
TOPLAS = journal("TOPLAS", "ACM Transactions on Programming Languages and Systems")
TOS = journal("TOS", "ACM Transacations on Storage")
TOSEM = journal("TOSEM", "ACM Transactions on Software Engineering and Methodology")
TPDL = conference("TPDL", "International Conference on Theory and Practice of Digital Libraries")
TRUST = conference("TRUST", "International Conference on Trust & Trustworthy Computing")
TSE = journal("TSE", "IEEE Transactions on Software Engineering")
TSMC = journal("TSMC", "IEEE Transactions on Systems, Man, and Cybernetics")
Tukey = conference("<Tukey>", "Princeton NJ, Tukey Centennial Workshop")
TVCG = journal("TVCG", "IEEE Transactions on Visualization and Computer Graphics")
TWEB = journal("TWEB", "ACM Transactions on the Web")

UAHCI = conference("UAHCI", "International Conference on Universal Access in Human-Computer Interaction")
UCC = conference("UCC", "International Conference on Utility and Cloud Computing")
UIC = conference("UIC", "International Conference on Ubiquitous and Intelligence Computing")
UIST = conference("UIST", "ACM Symposium on User Interface Software and Technology")
Ultramicroscopy = journal("Ultramicroscopy", "Ultramicroscopy")
UMAP = conference("UMAP", "International Conference on User Modeling, Adaptation, and Personalization")
UMUAI = journal("UMUAI", "User Modeling and User-Adapted Interaction")
URAL_PDC = conference("Ural-PDC", "Ural Workshop on Parallel, Distributed, and Cloud Computing for Young Scientists")
useR = conference("useR", "International R User Conference")
USITS = conference("USITS", "Usenix Symposium on Internet Technologies and Systems")

VAST = conference("VAST", "IEEE Conference on Visual Analytics Science and Technology")
VEE = conference("VEE", "ACM SIGPLAN/SIGOPS International Conference on Virtual Execution Environments")
VEM = conference("VEM", "Workshop on Software Visualization, Evolution and Maintenance")
VDA = conference("VDA", "Visualization and Data Analysis ")
VIS = conference("VIS", "IEEE VIS")
VISAP = conference("VISAP", "IEEE VIS Arts Program")
VLDB = conference("VLDB", "VLDB Endowment") # Very Large Data Bases
VLDB_Journal = journal("VLDB(J)", "Very Large Data Bases")
VLHCC = conference("VLHCC", "IEEE Symposiumon Visual Languages and Human-Centric Computing")
VMCAI = conference("VMCAI", "International Conference on Verification, Model Checking, and Abstract Interpretation")

WAFR = conference("WAFR", "International Workshop on the Algorithmic Foundations of Robotics")
WaterResourRes = journal("Water Resour. Res.", "Water Resources Research")
WBIA = conference("WBIA", "Workshop on Binary Instrumentation and Applications")
WCW = conference("WCW", "Web Caching and Content Distribution Workshop")
WDDP = conference("<WDDP>", "Workshop on Data Derivation and Provenance")
WebScience = conference("Web Science", "ACM Web Science Conference")
WebSemantics = journal("WebSemantics", "Web semantics: science, services and agents on the World Wide Web") # Journal of Web Semantics
WI_IAT = conference("WI-IAT", "International Conference on Web Intelligence and Intelligent Agent Technology")
WIAMIS = conference("WIAMIS", "International Workshop on Image Analysis for Multimedia Interactive Services")
WIMS = conference("WIMS", "International Conference on Web Intelligence, Mining and Semantics")
Winter = conference("<Winter>", "USENIX Winter Conference")
WIREsCS = journal("WIREsCS", "Wiley Interdisciplinary Reviews: Computational Statistics")
WISE = conference("WISE", "Web Information Systems Engineering Workshop")
WJMB = journal("WJMB", "World Journal of Microbiology and Biotechnology")
WHPCF = conference("WHPCF", "Workshop on High Performance Computational Finance")
WODA = conference("WODA", "International Workshop on Dynamic Analysis")
WoLE = conference("WoLE", "Web of Linked Entities")
WORKS = conference("WORKS", "Workshop on Workflows in Support of Large-Scale Science")
WPDD = conference("WPDD", "Workshop on Parralel & Distributed Debugging")
WRM = conference("WRM", "SPE Western Regional Meeting")
WSC = conference("WSC", "ISI World Statistics Congress")
WSC2 = conference("WSC", "Winter Simulation Conference")
WSDM = conference("WSDM", "International Conference on Web Search and Data Mining")
WWW = conference("WWWW", "International World Wide Web Conference")

XAP = journal("XAP", "Journal of Experimental Psychology: Applied")
XRDS = magazine("XRDS", "XRDS: Crossroads")
XSEDE = conference("XSEDE", "Conference of the Extreme Science and Engineering Discovery Environment")


arXiv = DB(Place("arXiv", "arXiv", "Archive"))
bioRxiv = DB(Place("bioRxiv", "bioRxiv", "Archive"))
Book = DB(Place("Book", "Book", "Book"))
PRBook = DB(Place("PRBook", "PRBook", "Peer Reviewed Book"))
Commerce = DB(Place("Commerce", "U.S. Department of Commerce", "Other"))
Lang = DB(Place("Lang", "Lang", "Lang"))
LangConf = conference("Lang", "<L A N G>")
LNCS = DB(Place("LNCS", "LNCS", "Proceedings"))
NSF = DB(Place("<NSF>", "National Science Foundations", "Sponsor"))
Patent = DB(Place("Patent", "Patent", "Patent"))
Standard = DB(Place("Standard", "Standard", "Standard"))
TechReport = DB(Place("Tech Report", "Tech Report", "Tech Report"))
Thesis = DB(Place("Thesis", "Thesis", "Thesis"))
Unpublished = DB(Place("Unpublished", "Unpublished", "Unpublished"))
W3C = DB(Place("W3C", "W3C Proposed Recommendation", "Standard"))
Web = DB(Place("Web", "Web", "Web"))